# Generated by Django 4.0.5 on 2022-06-20 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-Created_date']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='Created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='Published_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='Text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
